# Let’s Build First Real Pipeline

In [1]:
import numpy as np
import pandas as pd

data = {
    'Age' : [25, 30, np.nan, 35, 40],
    'Salary' : [50000, 60000, 55000, np.nan, 80000],
    'Purchased' : ['No', 'Yes', 'No', 'Yes', 'Yes']
}

df = pd.DataFrame(data)
df

    Age   Salary Purchased
0  25.0  50000.0        No
1  30.0  60000.0       Yes
2   NaN  55000.0        No
3  35.0      NaN       Yes
4  40.0  80000.0       Yes

# Split Data

In [9]:
from sklearn.model_selection import train_test_split
X = df[['Age','Salary']]
y = df['Purchased']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

# Build Preprocessing

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Numeric Pipeline

In [11]:
numeric_pipeline = Pipeline(steps=[('imputer', SimpleImputer(strategy='mean')),('scaler', StandardScaler())])

# ColumnTransformer

In [12]:
preprocessor = ColumnTransformer(transformers=[('num', numeric_pipeline, ['Age','Salary'])])

# Add Model Inside Pipeline

In [13]:
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline(steps=[('preprocessing', preprocessor),('model', LogisticRegression())])

# Train

In [26]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Salary'])])),
                ('model', LogisticRegression())])

# Predict

In [27]:
predictions = pipeline.predict(X_test)
print(predictions)

['No']

# SimpleImputer Example

In [28]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

data = {
    'Age': [25, 30, np.nan, 35, 40],
    'Salary': [50000, 60000, 55000, np.nan, 80000]
}

df = pd.DataFrame(data)
df

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2   NaN  55000.0
3  35.0      NaN
4  40.0  80000.0

In [36]:
# Mean Strategy
imputer_mean = SimpleImputer(strategy='mean')
df_mean = imputer_mean.fit_transform(df)

print("\nMean Imputed Data:\n", df_mean)

# Median Strategy
imputer_median = SimpleImputer(strategy='median')
df_median = imputer_median.fit_transform(df)

print("\nMedian Imputed Data:\n", df_median)

# Constant Strategy
imputer_constant = SimpleImputer(strategy='constant', fill_value=0)
df_constant = imputer_constant.fit_transform(df)

print("\nConstant Imputed Data:\n", df_constant)

# Add Indicator
imputer_indicator = SimpleImputer(strategy='mean', add_indicator=True)
df_indicator = imputer_indicator.fit_transform(df)

print("\nWith Missing Indicator:\n", df_indicator)

Mean Imputed Data:
 [[2.500e+01 5.000e+04]
 [3.000e+01 6.000e+04]
 [3.250e+01 5.500e+04]
 [3.500e+01 6.125e+04]
 [4.000e+01 8.000e+04]]

Median Imputed Data:
 [[2.50e+01 5.00e+04]
 [3.00e+01 6.00e+04]
 [3.25e+01 5.50e+04]
 [3.50e+01 5.75e+04]
 [4.00e+01 8.00e+04]]

Constant Imputed Data:
 [[2.5e+01 5.0e+04]
 [3.0e+01 6.0e+04]
 [0.0e+00 5.5e+04]
 [3.5e+01 0.0e+00]
 [4.0e+01 8.0e+04]]

With Missing Indicator:
 [[2.500e+01 5.000e+04 0.000e+00 0.000e+00]
 [3.000e+01 6.000e+04 0.000e+00 0.000e+00]
 [3.250e+01 5.500e+04 1.000e+00 0.000e+00]
 [3.500e+01 6.125e+04 0.000e+00 1.000e+00]
 [4.000e+01 8.000e+04 0.000e+00 0.000e+00]]

Mean → Normal distribution

Median → Skewed data

Most_frequent → Categorical

Constant → Domain rule

add_indicator=True → When missingness itself is informative

# KNN IMPUTER

In [41]:
from sklearn.impute import KNNImputer

imputer_knn = KNNImputer(n_neighbors=2)

df_knn = imputer_knn.fit_transform(df)

print("\nKNN Imputed Data:\n", df_knn)

KNN Imputed Data:
 [[2.50e+01 5.00e+04]
 [3.00e+01 6.00e+04]
 [2.75e+01 5.50e+04]
 [3.50e+01 7.00e+04]
 [4.00e+01 8.00e+04]]

# LABEL ENCODER

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = ['Yes', 'No', 'Yes', 'No']
encoded = le.fit_transform(y)

print("Encoded:", encoded)

Encoded: [1 0 1 0]

# ONEHOTENCODER

In [15]:
from sklearn.preprocessing import OneHotEncoder

data = [['Hyderabad'], ['Chennai'], ['Delhi']]

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded = encoder.fit_transform(data)

print(encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

✔ Nominal categorical variables
✔ Linear models
✔ Neural networks

# ORDINALENCODER

In [46]:
from sklearn.preprocessing import OrdinalEncoder

data = [['Junior'], ['Mid'], ['Senior']]

encoder = OrdinalEncoder(categories=[['Junior','Mid','Senior']])
encoded = encoder.fit_transform(data)

print(encoded)

[[0.]
 [1.]
 [2.]]

# COLUMNTRANSFORMER

In [28]:
import pandas as pd
import numpy as np

data = {
    'Age': [25, 30, np.nan, 35, 40, 28, 50, np.nan,45,49],
    'Salary': [50000, 60000, 55000, np.nan, 80000, 52000, 90000, 58000,95000,43000],
    'City': ['Hyd', 'Hyd', 'Chennai', 'Hyd', 'Delhi', 'Delhi', 'Chennai', 'Hyd','Blr','Mumbai'],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No','Yes','No']
}

df = pd.DataFrame(data)

print(df)

    Age   Salary     City Purchased
0  25.0  50000.0      Hyd        No
1  30.0  60000.0      Hyd       Yes
2   NaN  55000.0  Chennai        No
3  35.0      NaN      Hyd       Yes
4  40.0  80000.0    Delhi       Yes
5  28.0  52000.0    Delhi        No
6  50.0  90000.0  Chennai       Yes
7   NaN  58000.0      Hyd        No
8  45.0  95000.0      Blr       Yes
9  49.0  43000.0   Mumbai        No

In [33]:
import pandas as pd
import numpy as np

# ---------------- DATASET ----------------
data = {
    'Age': [25, 30, np.nan, 35, 40, 28, 50, np.nan,45,49],
    'Salary': [50000, 60000, 55000, np.nan, 80000, 52000, 90000, 58000,95000,43000],
    'City': ['Hyd', 'Hyd', 'Chennai', 'Hyd', 'Delhi', 'Delhi', 'Chennai', 'Hyd','Blr','Mumbai'],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No','Yes','No']
}


df = pd.DataFrame(data)

print(df)

# ---------------- FEATURES & TARGET ----------------
X = df.drop('Purchased', axis=1)
y = df['Purchased'].map({'No':0, 'Yes':1})   # convert to numeric

# ---------------- TRAIN TEST SPLIT ----------------
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# ---------------- PREPROCESSING ----------------
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

numeric_features = ['Age','Salary']
categorical_features = ['City']

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_features),
    ('cat', categorical_pipeline, categorical_features)
])

# ---------------- MODEL PIPELINE ----------------
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', LogisticRegression())
])

# ---------------- TRAIN ----------------
pipeline.fit(X_train, y_train)

# ---------------- PREDICT ----------------
predictions = pipeline.predict(X_test)
print(X_test)
print("\nPredictions:", predictions)

    Age   Salary     City Purchased
0  25.0  50000.0      Hyd        No
1  30.0  60000.0      Hyd       Yes
2   NaN  55000.0  Chennai        No
3  35.0      NaN      Hyd       Yes
4  40.0  80000.0    Delhi       Yes
5  28.0  52000.0    Delhi        No
6  50.0  90000.0  Chennai       Yes
7   NaN  58000.0      Hyd        No
8  45.0  95000.0      Blr       Yes
9  49.0  43000.0   Mumbai        No
    Age   Salary   City
8  45.0  95000.0    Blr
1  30.0  60000.0    Hyd
5  28.0  52000.0  Delhi

Predictions: [1 0 0]

# CUSTOM TRANSFORMER

In [58]:
# Example: Create Age_Group Feature
from sklearn.base import BaseEstimator, TransformerMixin

class AgeGroupTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        X['Age_Group'] = X['Age'] // 10
        return X

| Tool               | Use                       |
| ------------------ | ------------------------- |
| SimpleImputer      | Basic missing             |
| KNNImputer         | Pattern-based missing     |
| LabelEncoder       | Target only               |
| OneHotEncoder      | Nominal categorical       |
| OrdinalEncoder     | Ordered categorical       |
| ColumnTransformer  | Column-wise preprocessing |
| Pipeline           | Avoid data leakage        |
| Custom Transformer | Custom feature logic      |

# HANDS ON PRACTISE ( DATA CLEANING + DATA PREPROCESSING)

In [70]:
import numpy as np
import pandas as pd

data = {
    "Age": [25, 30, 22, 35, 40, np.nan, 28, 32, 45, 29, 50, 27],
    "Salary": [50000, 60000, 45000, np.nan, 80000, 52000, 48000, 62000, 90000, -1, 120000, 55000],
    "City": ["Hyderabad", "Chennai", "Delhi", "Mumbai", np.nan, 
             "Hyderabad", "Delhi", "Chennai", "Mumbai", "Delhi", "Hyderabad", "Chennai"],
    "Education_Level": ["Bachelor", "Master", "Bachelor", "PhD", "Master",
                        "Bachelor", "Master", "PhD", "Bachelor", "Master", "PhD", None],
    "Experience_Level": ["Junior", "Mid", "Junior", "Senior", "Senior","Mid", "Junior", "Senior", "Mid", "Junior", "Senior", "Mid"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes", "No", "No", "Yes", "Yes", "No", "Yes", "No"]
}

df = pd.DataFrame(data)

print("Dataset Preview:\n")
print(df)
print("\nData Types:\n")
print(df.dtypes)

Dataset Preview:

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  Hyderabad        Bachelor           Junior        No
1   30.0   60000.0    Chennai          Master              Mid       Yes
2   22.0   45000.0      Delhi        Bachelor           Junior        No
3   35.0       NaN     Mumbai             PhD           Senior       Yes
4   40.0   80000.0        NaN          Master           Senior       Yes
5    NaN   52000.0  Hyderabad        Bachelor              Mid        No
6   28.0   48000.0      Delhi          Master           Junior        No
7   32.0   62000.0    Chennai             PhD           Senior       Yes
8   45.0   90000.0     Mumbai        Bachelor              Mid       Yes
9   29.0      -1.0      Delhi          Master           Junior        No
10  50.0  120000.0  Hyderabad             PhD           Senior       Yes
11  27.0   55000.0    Chennai            None              Mid        No

Data Types:

Age                 float64
Salary              float64
City                 object
Education_Level      object
Experience_Level     object
Purchased            object
dtype: object

In [71]:
# Check Missing Values
print(df.isnull().sum())

Age                 1
Salary              1
City                1
Education_Level     1
Experience_Level    0
Purchased           0
dtype: int64

In [72]:
print(df.isna().sum())

Age                 1
Salary              1
City                1
Education_Level     1
Experience_Level    0
Purchased           0
dtype: int64

In [73]:
# Handle Invalid Values
df['Salary'] = df['Salary'].replace(-1.0,np.nan)
print(df.isnull().sum())

Age                 1
Salary              2
City                1
Education_Level     1
Experience_Level    0
Purchased           0
dtype: int64

In [74]:
# Remove Duplicates
df.drop_duplicates(inplace = True)
df.shape

(12, 6)

In [75]:
# Fix Categorical Inconsistency
df['Purchased'] = df['Purchased'].str.lower()
df['City'] = df['City'].str.lower()
df['Education_Level'] = df['Education_Level'].str.lower()

In [76]:
# Data Type Check
print(df.dtypes)

Age                 float64
Salary              float64
City                 object
Education_Level      object
Experience_Level     object
Purchased            object
dtype: object

In [77]:
df

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  hyderabad        bachelor           Junior        no
1   30.0   60000.0    chennai          master              Mid       yes
2   22.0   45000.0      delhi        bachelor           Junior        no
3   35.0       NaN     mumbai             phd           Senior       yes
4   40.0   80000.0        NaN          master           Senior       yes
5    NaN   52000.0  hyderabad        bachelor              Mid        no
6   28.0   48000.0      delhi          master           Junior        no
7   32.0   62000.0    chennai             phd           Senior       yes
8   45.0   90000.0     mumbai        bachelor              Mid       yes
9   29.0       NaN      delhi          master           Junior        no
10  50.0  120000.0  hyderabad             phd           Senior       yes
11  27.0   55000.0    chennai            None              Mid        no

In [78]:
# Handle Missing Numerical Values using Pandas
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['City'] = df['City'].fillna(df['City'].mode()[0])
df

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  hyderabad        bachelor           Junior        no
1   30.0   60000.0    chennai          master              Mid       yes
2   22.0   45000.0      delhi        bachelor           Junior        no
3   35.0   66200.0     mumbai             phd           Senior       yes
4   40.0   80000.0    chennai          master           Senior       yes
5   33.0   52000.0  hyderabad        bachelor              Mid        no
6   28.0   48000.0      delhi          master           Junior        no
7   32.0   62000.0    chennai             phd           Senior       yes
8   45.0   90000.0     mumbai        bachelor              Mid       yes
9   29.0   66200.0      delhi          master           Junior        no
10  50.0  120000.0  hyderabad             phd           Senior       yes
11  27.0   55000.0    chennai            None              Mid        no

In [79]:
import numpy as np
import pandas as pd

data = {
    "Age": [25, 30, 22, 35, 40, np.nan, 28, 32, 45, 29, 50, 27],
    "Salary": [50000, 60000, 45000, np.nan, 80000, 52000, 48000, 62000, 90000, -1, 120000, 55000],
    "City": ["Hyderabad", "Chennai", "Delhi", "Mumbai", np.nan, 
             "Hyderabad", "Delhi", "Chennai", "Mumbai", "Delhi", "Hyderabad", "Chennai"],
    "Education_Level": ["Bachelor", "Master", "Bachelor", "PhD", "Master",
                        "Bachelor", "Master", "PhD", "Bachelor", "Master", "PhD", None],
    "Experience_Level": ["Junior", "Mid", "Junior", "Senior", "Senior","Mid", "Junior", "Senior", "Mid", "Junior", "Senior", "Mid"],
    "Purchased": ["No", "Yes", "No", "Yes", "Yes", "No", "No", "Yes", "Yes", "No", "Yes", "No"]
}

df1 = pd.DataFrame(data)

print("Dataset Preview:\n")
print(df1)
print("\nData Types:\n")
print(df1.dtypes)

Dataset Preview:

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  Hyderabad        Bachelor           Junior        No
1   30.0   60000.0    Chennai          Master              Mid       Yes
2   22.0   45000.0      Delhi        Bachelor           Junior        No
3   35.0       NaN     Mumbai             PhD           Senior       Yes
4   40.0   80000.0        NaN          Master           Senior       Yes
5    NaN   52000.0  Hyderabad        Bachelor              Mid        No
6   28.0   48000.0      Delhi          Master           Junior        No
7   32.0   62000.0    Chennai             PhD           Senior       Yes
8   45.0   90000.0     Mumbai        Bachelor              Mid       Yes
9   29.0      -1.0      Delhi          Master           Junior        No
10  50.0  120000.0  Hyderabad             PhD           Senior       Yes
11  27.0   55000.0    Chennai            None              Mid        No

Data Types:

Age                 float64
Salary              float64
City                 object
Education_Level      object
Experience_Level     object
Purchased            object
dtype: object

In [80]:
# Handle Missing Numerical Values using Imputer
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'median')
df1[['Age','Salary']] = imputer.fit_transform(df1[['Age','Salary']])
df1['Education_Level'] = df1['Education_Level'].replace({None: np.nan})
# here no need to fill categorical column because all value exist
# Handle Missing Values (Categorical)
cat_imputer = SimpleImputer(strategy='most_frequent')

df1[['City', 'Education_Level']] = cat_imputer.fit_transform(
    df1[['City', 'Education_Level']])

print(df1[['City', 'Education_Level']])

         City Education_Level
0   Hyderabad        Bachelor
1     Chennai          Master
2       Delhi        Bachelor
3      Mumbai             PhD
4     Chennai          Master
5   Hyderabad        Bachelor
6       Delhi          Master
7     Chennai             PhD
8      Mumbai        Bachelor
9       Delhi          Master
10  Hyderabad             PhD
11    Chennai        Bachelor

In [81]:
# outlier detection ( IQR METHOD )
cols = ['Age','Salary']
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3-Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound)| (df[col] > upper_bound)]
    print(outliers)

     Age    Salary       City Education_Level Experience_Level Purchased
10  50.0  120000.0  hyderabad             phd           Senior       yes
     Age    Salary       City Education_Level Experience_Level Purchased
10  50.0  120000.0  hyderabad             phd           Senior       yes

In [82]:
# Check Imbalance
print(df['Purchased'].value_counts())
df

Purchased
no     6
yes    6
Name: count, dtype: int64

     Age    Salary       City Education_Level Experience_Level Purchased
0   25.0   50000.0  hyderabad        bachelor           Junior        no
1   30.0   60000.0    chennai          master              Mid       yes
2   22.0   45000.0      delhi        bachelor           Junior        no
3   35.0   66200.0     mumbai             phd           Senior       yes
4   40.0   80000.0    chennai          master           Senior       yes
5   33.0   52000.0  hyderabad        bachelor              Mid        no
6   28.0   48000.0      delhi          master           Junior        no
7   32.0   62000.0    chennai             phd           Senior       yes
8   45.0   90000.0     mumbai        bachelor              Mid       yes
9   29.0   66200.0      delhi          master           Junior        no
10  50.0  120000.0  hyderabad             phd           Senior       yes
11  27.0   55000.0    chennai            None              Mid        no

In [83]:
# DATA PREPROCESSING (SCIKIT-LEARN)
# Split Data
from sklearn.model_selection import train_test_split

X = df.drop('Purchased', axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (9, 5)
Test shape: (3, 5)

In [84]:
# Define Column Groups
numeric_features = ['Age', 'Salary']
nominal_features = ['City', 'Education_Level']
ordinal_features = ['Experience_Level']

In [85]:
# Numeric Pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
numeric_pipeline = Pipeline([('scaler', StandardScaler())])

In [86]:
# Nominal Encoding
from sklearn.preprocessing import OneHotEncoder

nominal_pipeline = Pipeline([('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [87]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

ordinal_pipeline = Pipeline([('encoder', OrdinalEncoder(categories=[['Junior','Mid','Senior']]))])

In [88]:
# Combine Using ColumnTransformer
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_features),
    ('nom', nominal_pipeline, nominal_features),
    ('ord', ordinal_pipeline, ordinal_features)
])

In [89]:
# Add Model to Pipeline
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([('preprocessing', preprocessor),('model', LogisticRegression())])

In [90]:
# Train Model
pipeline.fit(X_train, y_train)
print("Model trained successfully.")

Model trained successfully.

In [116]:
# Predict
y_pred = pipeline.predict(X_test)
print("Predictions:", y_pred)
print("Actual:", y_test.values)

Predictions: ['yes' 'no' 'no']
Actual: ['yes' 'no' 'no']

In [117]:
# Evaluate
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

          no       1.00      1.00      1.00         2
         yes       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

MEMORY MAP

DATA CLEANING:

Check missing

Replace invalid

Remove duplicates

Standardize text

Fix datatypes

Detect outliers

Impute numeric

Impute categorical

Check imbalance

DATA PREPROCESSING:

Train-test split

Define numeric / nominal / ordinal

Build pipelines

ColumnTransformer

Final pipeline

Fit

Predict

Evaluate